version: '2'
services:
  base:
    build: .
    image: ropelive/rest
    restart: on-failure

  rest:
    extends: base
    ports:
    - "3435:3435"
    command: npm start
    environment:
    - "REST_PORT=3435"
    - "REST_TIMEOUT=10000"
